# Generated by Django 4.1.5 on 2023-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attack_power', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
